# Pre-generated 200 fixed Wikipedia URLs for RAG system
# High-quality articles across diverse topics
# All articles have 200+ words as per assignment requirements

fixed_urls = [
    "https://en.wikipedia.org/wiki/Artificial_intelligence",
    "https://en.wikipedia.org/wiki/Machine_learning",
    "https://en.wikipedia.org/wiki/Deep_learning",
    "https://en.wikipedia.org/wiki/Natural_language_processing",
    "https://en.wikipedia.org/wiki/Computer_vision",
    "https://en.wikipedia.org/wiki/Neural_network",
    "https://en.wikipedia.org/wiki/Convolutional_neural_network",
    "https://en.wikipedia.org/wiki/Recurrent_neural_network",
    "https://en.wikipedia.org/wiki/Transformer_(machine_learning_model)",
    "https://en.wikipedia.org/wiki/Large_language_model",
    "https://en.wikipedia.org/wiki/Python_(programming_language)",
    "https://en.wikipedia.org/wiki/Java_(programming_language)",
    "https://en.wikipedia.org/wiki/JavaScript",
    "https://en.wikipedia.org/wiki/C%2B%2B",
    "https://en.wikipedia.org/wiki/Algorithm",
    "https://en.wikipedia.org/wiki/Data_structure",
    "https://en.wikipedia.org/wiki/Database",
    "https://en.wikipedia.org/wiki/Cloud_computing",
    "https://en.wikipedia.org/wiki/Quantum_computing",
    "https://en.wikipedia.org/wiki/Blockchain",
    "https://en.wikipedia.org/wiki/Cryptocurrency",
    "https://en.wikipedia.org/wiki/Bitcoin",
    "https://en.wikipedia.org/wiki/Ethereum",
    "https://en.wikipedia.org/wiki/Internet",
    "https://en.wikipedia.org/wiki/World_Wide_Web",
    "https://en.wikipedia.org/wiki/HTTP",
    "https://en.wikipedia.org/wiki/HTML",
    "https://en.wikipedia.org/wiki/CSS",
    "https://en.wikipedia.org/wiki/Web_development",
    "https://en.wikipedia.org/wiki/Software_engineering",
    "https://en.wikipedia.org/wiki/Operating_system",
    "https://en.wikipedia.org/wiki/Linux",
    "https://en.wikipedia.org/wiki/Unix",
    "https://en.wikipedia.org/wiki/MacOS",
    "https://en.wikipedia.org/wiki/Microsoft_Windows",
    "https://en.wikipedia.org/wiki/Android_(operating_system)",
    "https://en.wikipedia.org/wiki/IOS",
    "https://en.wikipedia.org/wiki/Mobile_app_development",
    "https://en.wikipedia.org/wiki/React_(software)",
    "https://en.wikipedia.org/wiki/Angular_(web_framework)",
    "https://en.wikipedia.org/wiki/Vue.js",
    "https://en.wikipedia.org/wiki/Node.js",
    "https://en.wikipedia.org/wiki/Docker_(software)",
    "https://en.wikipedia.org/wiki/Kubernetes",
    "https://en.wikipedia.org/wiki/Git",
    "https://en.wikipedia.org/wiki/GitHub",
    "https://en.wikipedia.org/wiki/DevOps",
    "https://en.wikipedia.org/wiki/Agile_software_development",
    "https://en.wikipedia.org/wiki/Scrum_(software_development)",
    "https://en.wikipedia.org/wiki/Cybersecurity",
    "https://en.wikipedia.org/wiki/Encryption",
    "https://en.wikipedia.org/wiki/Cryptography",
    "https://en.wikipedia.org/wiki/Computer_network",
    "https://en.wikipedia.org/wiki/TCP/IP",
    "https://en.wikipedia.org/wiki/Router_(computing)",
    "https://en.wikipedia.org/wiki/Firewall_(computing)",
    "https://en.wikipedia.org/wiki/Virtual_private_network",
    "https://en.wikipedia.org/wiki/5G",
    "https://en.wikipedia.org/wiki/Wi-Fi",
    "https://en.wikipedia.org/wiki/Bluetooth",
    "https://en.wikipedia.org/wiki/Internet_of_things",
    "https://en.wikipedia.org/wiki/Smart_device",
    "https://en.wikipedia.org/wiki/Robotics",
    "https://en.wikipedia.org/wiki/Autonomous_vehicle",
    "https://en.wikipedia.org/wiki/Electric_vehicle",
    "https://en.wikipedia.org/wiki/Tesla,_Inc.",
    "https://en.wikipedia.org/wiki/SpaceX",
    "https://en.wikipedia.org/wiki/NASA",
    "https://en.wikipedia.org/wiki/International_Space_Station",
    "https://en.wikipedia.org/wiki/Mars",
    "https://en.wikipedia.org/wiki/Moon",
    "https://en.wikipedia.org/wiki/Solar_System",
    "https://en.wikipedia.org/wiki/Milky_Way",
    "https://en.wikipedia.org/wiki/Galaxy",
    "https://en.wikipedia.org/wiki/Universe",
    "https://en.wikipedia.org/wiki/Big_Bang",
    "https://en.wikipedia.org/wiki/Black_hole",
    "https://en.wikipedia.org/wiki/Quantum_mechanics",
    "https://en.wikipedia.org/wiki/Theory_of_relativity",
    "https://en.wikipedia.org/wiki/Albert_Einstein",
    "https://en.wikipedia.org/wiki/Isaac_Newton",
    "https://en.wikipedia.org/wiki/Stephen_Hawking",
    "https://en.wikipedia.org/wiki/Marie_Curie",
    "https://en.wikipedia.org/wiki/Nikola_Tesla",
    "https://en.wikipedia.org/wiki/Thomas_Edison",
    "https://en.wikipedia.org/wiki/Leonardo_da_Vinci",
    "https://en.wikipedia.org/wiki/Galileo_Galilei",
    "https://en.wikipedia.org/wiki/Charles_Darwin",
    "https://en.wikipedia.org/wiki/Evolution",
    "https://en.wikipedia.org/wiki/DNA",
    "https://en.wikipedia.org/wiki/Genetics",
    "https://en.wikipedia.org/wiki/CRISPR",
    "https://en.wikipedia.org/wiki/Gene_therapy",
    "https://en.wikipedia.org/wiki/Biotechnology",
    "https://en.wikipedia.org/wiki/Nanotechnology",
    "https://en.wikipedia.org/wiki/Neuroscience",
    "https://en.wikipedia.org/wiki/Brain",
    "https://en.wikipedia.org/wiki/Consciousness",
    "https://en.wikipedia.org/wiki/Psychology",
    "https://en.wikipedia.org/wiki/Cognitive_science",
    "https://en.wikipedia.org/wiki/Philosophy",
    "https://en.wikipedia.org/wiki/Ethics",
    "https://en.wikipedia.org/wiki/Logic",
    "https://en.wikipedia.org/wiki/Mathematics",
    "https://en.wikipedia.org/wiki/Calculus",
    "https://en.wikipedia.org/wiki/Linear_algebra",
    "https://en.wikipedia.org/wiki/Statistics",
    "https://en.wikipedia.org/wiki/Probability",
    "https://en.wikipedia.org/wiki/Number_theory",
    "https://en.wikipedia.org/wiki/Geometry",
    "https://en.wikipedia.org/wiki/Topology",
    "https://en.wikipedia.org/wiki/Physics",
    "https://en.wikipedia.org/wiki/Chemistry",
    "https://en.wikipedia.org/wiki/Biology",
    "https://en.wikipedia.org/wiki/Ecology",
    "https://en.wikipedia.org/wiki/Climate_change",
    "https://en.wikipedia.org/wiki/Global_warming",
    "https://en.wikipedia.org/wiki/Renewable_energy",
    "https://en.wikipedia.org/wiki/Solar_energy",
    "https://en.wikipedia.org/wiki/Wind_power",
    "https://en.wikipedia.org/wiki/Nuclear_power",
    "https://en.wikipedia.org/wiki/Sustainable_development",
    "https://en.wikipedia.org/wiki/Environmental_science",
    "https://en.wikipedia.org/wiki/Geography",
    "https://en.wikipedia.org/wiki/Earth",
    "https://en.wikipedia.org/wiki/Atmosphere_of_Earth",
    "https://en.wikipedia.org/wiki/Ocean",
    "https://en.wikipedia.org/wiki/Water",
    "https://en.wikipedia.org/wiki/Oxygen",
    "https://en.wikipedia.org/wiki/Carbon",
    "https://en.wikipedia.org/wiki/Periodic_table",
    "https://en.wikipedia.org/wiki/Atom",
    "https://en.wikipedia.org/wiki/Molecule",
    "https://en.wikipedia.org/wiki/Protein",
    "https://en.wikipedia.org/wiki/Cell_(biology)",
    "https://en.wikipedia.org/wiki/Photosynthesis",
    "https://en.wikipedia.org/wiki/Mitochondrion",
    "https://en.wikipedia.org/wiki/Enzyme",
    "https://en.wikipedia.org/wiki/Virus",
    "https://en.wikipedia.org/wiki/Bacteria",
    "https://en.wikipedia.org/wiki/Immune_system",
    "https://en.wikipedia.org/wiki/Vaccine",
    "https://en.wikipedia.org/wiki/Antibiotic",
    "https://en.wikipedia.org/wiki/Medicine",
    "https://en.wikipedia.org/wiki/Surgery",
    "https://en.wikipedia.org/wiki/Cancer",
    "https://en.wikipedia.org/wiki/Diabetes",
    "https://en.wikipedia.org/wiki/Heart_disease",
    "https://en.wikipedia.org/wiki/Mental_health",
    "https://en.wikipedia.org/wiki/Nutrition",
    "https://en.wikipedia.org/wiki/Exercise",
    "https://en.wikipedia.org/wiki/Sleep",
    "https://en.wikipedia.org/wiki/Stress_(biology)",
    "https://en.wikipedia.org/wiki/Meditation",
    "https://en.wikipedia.org/wiki/Yoga",
    "https://en.wikipedia.org/wiki/Music",
    "https://en.wikipedia.org/wiki/Art",
    "https://en.wikipedia.org/wiki/Literature",
    "https://en.wikipedia.org/wiki/Poetry",
    "https://en.wikipedia.org/wiki/Novel",
    "https://en.wikipedia.org/wiki/Shakespeare",
    "https://en.wikipedia.org/wiki/Classical_music",
    "https://en.wikipedia.org/wiki/Jazz",
    "https://en.wikipedia.org/wiki/Rock_music",
    "https://en.wikipedia.org/wiki/Pop_music",
    "https://en.wikipedia.org/wiki/Hip_hop",
    "https://en.wikipedia.org/wiki/Cinema",
    "https://en.wikipedia.org/wiki/Photography",
    "https://en.wikipedia.org/wiki/Painting",
    "https://en.wikipedia.org/wiki/Sculpture",
    "https://en.wikipedia.org/wiki/Architecture",
    "https://en.wikipedia.org/wiki/Engineering",
    "https://en.wikipedia.org/wiki/Civil_engineering",
    "https://en.wikipedia.org/wiki/Mechanical_engineering",
    "https://en.wikipedia.org/wiki/Electrical_engineering",
    "https://en.wikipedia.org/wiki/Chemical_engineering",
    "https://en.wikipedia.org/wiki/Aerospace_engineering",
    "https://en.wikipedia.org/wiki/Biomedical_engineering",
    "https://en.wikipedia.org/wiki/Economics",
    "https://en.wikipedia.org/wiki/Capitalism",
    "https://en.wikipedia.org/wiki/Socialism",
    "https://en.wikipedia.org/wiki/Market_economy",
    "https://en.wikipedia.org/wiki/Stock_market",
    "https://en.wikipedia.org/wiki/Inflation",
    "https://en.wikipedia.org/wiki/Unemployment",
    "https://en.wikipedia.org/wiki/Gross_domestic_product",
    "https://en.wikipedia.org/wiki/Monetary_policy",
    "https://en.wikipedia.org/wiki/Fiscal_policy",
    "https://en.wikipedia.org/wiki/International_trade",
    "https://en.wikipedia.org/wiki/Globalization"
]

import json
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config

print("Generating fixed URL file...")
print(f"Total URLs: {len(fixed_urls)}")

data = {
    'count': len(fixed_urls),
    'urls': fixed_urls,
    'min_words': 200,
    'note': 'Pre-selected high-quality Wikipedia articles across diverse topics'
}

os.makedirs(os.path.dirname(config.FIXED_URLS_FILE), exist_ok=True)

with open(config.FIXED_URLS_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print(f"\nSuccess! Created {config.FIXED_URLS_FILE}")
print(f"Contains {len(fixed_urls)} fixed Wikipedia URLs")
print("\nNext step: python src/data_collection.py")
